import type { Metadata } from "next";

import BreakpointIndicator from "@/components/dev/breakpoint-indicator";
import Navbar from "@/components/layout/navbar";
import { plusJakarta } from "@/fonts";

import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Ziron Media - Digital Marketing Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plusJakarta.className} antialiased`}>
        <Navbar />
        {children}
        <BreakpointIndicator />
      </body>
    </html>
  );
}
