import type { Metadata } from "next";

import { ClerkProvider } from "@clerk/nextjs";

import BreakpointIndicator from "@/components/dev/breakpoint-indicator";
import LenisProvider from "@/components/dev/lenis";
import Footer from "@/components/layout/footer";
import Navbar from "@/components/layout/navbar";
import { monaSans, plusJakarta } from "@/fonts";
import { cn } from "@/lib/utils";

import "../styles/globals.css";
import "../styles/ui.css";

export const metadata: Metadata = {
  title: "Ziron Media - Digital Marketing Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(plusJakarta.className, monaSans.variable, "antialiased")}
      >
        <ClerkProvider>
          <div vaul-drawer-wrapper="">
            <LenisProvider />
            <Navbar />
            {children}
            <Footer />
            <BreakpointIndicator />
          </div>
        </ClerkProvider>
      </body>
    </html>
  );
}
